- name: Create MongoDB admin user
  hosts: all
  become: true
  vars:
    mongo_db_admin_user: root
    mongo_db_admin_password: password
  tasks:
    - name: Install pymongo
      ansible.builtin.pip:
        name: pymongo
        state: present
        extra_args: --break-system-packages

    - name: Ensure root user exists in admin database
      community.mongodb.mongodb_user:
        login_host: 127.0.0.1
        login_port: 27017
        database: admin
        name: "{{ mongo_db_admin_user }}"
        password: "{{ mongo_db_admin_password }}"
        roles:
          - db: admin
            role: root
        state: present
