FROM maven:3.9.13-eclipse-temurin-11 AS Builder

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests  && \
    echo "✅ JAR created:" && \
    ls -lh /app/target/*.jar

FROM eclipse-temurin:11-jre AS Runner

COPY --from=Builder /app/target/*.jar app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar", \
     "--spring.data.mongodb.username=root", \
     "--spring.data.mongodb.password=password"]
