- name: Remove all the installed files
  hosts: all
  become: true
  tasks:
    - name: Stop and Disable mongo
      ansible.builtin.systemd_service:
        name: mongod
        state: stopped
        enabled: false

    - name: Kill any running mongod processes
      ansible.builtin.shell: pkill -f mongod
      ignore_errors: yes

    - name: remove all the installed packages
      ansible.builtin.apt:
        name:
          - mongodb-org
          - mongodb-org-server
          - mongodb-org-shell
          - mongodb-org-mongos
          - mongodb-org-tools
          - mongodb-mongosh
          - openjdk-11-jdk
          - maven
          - nodejs
          - npm
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove all the files previously there
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/mongodb
        - /var/log/mongodb
        - /etc/mongod.conf
        - /tmp/mongodb-27017.sock
        - /tmp/mongodb*.sock
        - /etc/apt/sources.list.d/mongodb-org-8.0.list
        - /usr/share/keyrings/mongodb-server-8.0.gpg
        - /etc/apt/sources.list.d/nodesource.list
        - /etc/apt/sources.list.d/nodesource-node20.list
        - /etc/apt/sources.list.d/nodejs*
        - /usr/share/keyrings/nodesource.gpg
        - /etc/apt/preferences.d/nodejs
        - /etc/apt/preferences.d/nsolid
        - /var/lib/apt/lists/*

    - name: clean the APT
      ansible.builtin.apt:
        clean: true

    - name: Add primary DNS server
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "{{ item  }}"
        state: present
        create: yes
      loop:
        - "nameserver 8.8.8.8"
        - "nameserver 8.8.4.4"

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
